OCR_SPACE_KEY = "K85159395488957"
OPENAI_API_KEY = "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"
