OCR_SPACE_KEY = "K85159395488957"
OPENAI_API_KEY = "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"
